# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBooking():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_booking(self):
    self.driver.get("https://www.booking.com/index.en-gb.html?label=gen173nr-1BCAEoggI46AdIM1gEaMABiAEBmAEJuAEXyAEM2AEB6AEBiAIBqAIDuALS3qejBsACAdICJDFjZDc0M2NkLTllNmMtNDhiZS1hOTk4LWZkMDA0ZmFjOTE4Y9gCBeACAQ&sid=e9eeb29be9f137f937c8037ed648943c&keep_landing=1&sb_price_type=total&")
    self.driver.set_window_size(968, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".d4e829796c").click()
    self.driver.find_element(By.ID, ":Ra9:").send_keys("Halkidiki")
    self.driver.find_element(By.ID, ":Ra9:").click()
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.CSS_SELECTOR, ".f5ac4a5021").click()
    self.driver.find_element(By.CSS_SELECTOR, ".c938084447 > .e57ffa4eb5").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".c938084447 > .e57ffa4eb5")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
